In [139]:
import pandas as pd
import nltk

In [140]:
data = pd.read_csv("C:/Users/lenovo/Desktop/NLP/Datasets/Scrap6000.csv")

In [141]:
data.head()

,Unnamed: 0,author,statement,source,date,target,BinaryTarget,BinaryNumTarget
0,0,Kwasi Gyamfi,"""Samsung drops out of $1 billion advertising c...",Facebook posts,"• August 2,",FALSE,FAKE,0
1,1,Marta Campabadal,"""Mark Zuckerberg, CEO de Meta, ha retirado la ...",Facebook posts,"• August 2,",FALSE,FAKE,0
2,2,Maria Briceño,El 31 de julio de 2024 confirmaron el fallecim...,Facebook posts,"August 2, 2024",FALSE,FAKE,0
3,3,Jill Terreri,Biden Executive Order 14019 “requires our taxp...,Claudia Tenney,"• August 2,",pants-fire,REAL,1
4,4,Sara Swann,Vice President Kamala Harris “was born in Cana...,Threads posts,"August 1, 2024",pants-fire,REAL,1

In [142]:
data.dtypes

Unnamed: 0          int64
author             object
statement          object
source             object
date               object
target             object
BinaryTarget       object
BinaryNumTarget     int64
dtype: object

In [143]:
data.isnull().sum()

Unnamed: 0         0
author             0
statement          0
source             0
date               0
target             0
BinaryTarget       0
BinaryNumTarget    0
dtype: int64

In [144]:
len(max(data))

6

In [145]:
len(min(data))

15

word tokenization

In [146]:
from nltk import word_tokenize

data['word_tokenize'] = data['statement'].apply(word_tokenize)

In [147]:
data.head()

,Unnamed: 0,author,statement,source,date,target,BinaryTarget,BinaryNumTarget,word_tokenize
0,0,Kwasi Gyamfi,"""Samsung drops out of $1 billion advertising c...",Facebook posts,"• August 2,",FALSE,FAKE,0,"[``, Samsung, drops, out, of, $, 1, billion, a..."
1,1,Marta Campabadal,"""Mark Zuckerberg, CEO de Meta, ha retirado la ...",Facebook posts,"• August 2,",FALSE,FAKE,0,"[``, Mark, Zuckerberg, ,, CEO, de, Meta, ,, ha..."
2,2,Maria Briceño,El 31 de julio de 2024 confirmaron el fallecim...,Facebook posts,"August 2, 2024",FALSE,FAKE,0,"[El, 31, de, julio, de, 2024, confirmaron, el,..."
3,3,Jill Terreri,Biden Executive Order 14019 “requires our taxp...,Claudia Tenney,"• August 2,",pants-fire,REAL,1,"[Biden, Executive, Order, 14019, “, requires, ..."
4,4,Sara Swann,Vice President Kamala Harris “was born in Cana...,Threads posts,"August 1, 2024",pants-fire,REAL,1,"[Vice, President, Kamala, Harris, “, was, born..."

In [148]:
data['word_tokenize'][1]

['``',
 'Mark',
 'Zuckerberg',
 ',',
 'CEO',
 'de',
 'Meta',
 ',',
 'ha',
 'retirado',
 'la',
 'verificación',
 '”',
 'de',
 'Nicolás',
 'Maduro',
 'en',
 'Facebook',
 'e',
 'Instagram',
 '.']

sentence tokenization

In [149]:
from nltk import sent_tokenize

data['sentence_tokenization'] = data['statement'].apply(sent_tokenize)

In [151]:
data['sentence_tokenization'][54]

['Fox News aired a chyron that said, “Kamala could be the oldest elected female president.”']

lemmatization

In [152]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [172]:
import string
lemmatized_sentences = []

for text in data['statement']:
    words = word_tokenize(text)
    words = [word for word in words if word not in string.punctuation]
    stemmed_words = [lemmatizer.lemmatize(word) for word in words]
    stemmed_sentence = ' '.join(stemmed_words)
    lemmatized_sentences.append(stemmed_sentence)
    
data['lemmatized'] = lemmatized_sentences

In [179]:
data['lemmatized'][1223]

"Thanks to negotiating drug price `` our senior instead of paying 500 a month for drug are paying no more than 35 cent ''"

In [180]:
data['statement'][1223]

'Thanks to negotiating drug prices "our seniors, instead of paying $500 a month for drugs, are paying no more than 35 cents."'

stemming

In [161]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

In [165]:
import string

stemmed_sentences = []

for text in data['statement']:
    words = word_tokenize(text)
    words = [word for word in words if word not in string.punctuation]
    stemmed_words = [stemmer.stem(word) for word in words]
    stemmed_sentence = ' '.join(stemmed_words)
    stemmed_sentences.append(stemmed_sentence)
data['stemming'] = stemmed_sentences

In [169]:
data['stemming'][23]

'video show “ sever mask men storm a local vote station and stole the ballot box ” in venezuela ’ s 2024 elect'

In [170]:
data['statement'][23]

'Video shows “several masked men stormed a local voting station and stole the ballot boxes” in Venezuela’s 2024 election.'

N-gram extraction(unigram, bigram, tigram)

In [183]:
from nltk.util import ngrams


unigram_list = []
bigram_list = []
trigram_list = []


for text in(data['statement']):
    words = word_tokenize(text)
    
    unigram = list(ngrams(words, 1))
    bigram = list(ngrams(words, 2))
    trigram = list(ngrams(words, 3))
    
    unigram_list.append(' '.join([' '.join(gram) for gram in unigram]))
    bigram_list.append(' '.join([' '.join(gram) for gram in bigram]))
    trigram_list.append(' '.join([' '.join(gram) for gram in trigram]))

In [184]:
data['unigram'] = unigram_list
data['bigram'] = bigram_list
data['trigram'] = trigram_list

In [230]:
data['unigram'][3]

'Biden Executive Order 14019 “ requires our taxpayer-funded federal agencies to violate the Hatch Act and engage in illegal vote harvesting . ”'

In [190]:
data['bigram'][3]

'Biden Executive Executive Order Order 14019 14019 “ “ requires requires our our taxpayer-funded taxpayer-funded federal federal agencies agencies to to violate violate the the Hatch Hatch Act Act and and engage engage in in illegal illegal vote vote harvesting harvesting . . ”'

In [191]:
data['trigram'][3]

'Biden Executive Order Executive Order 14019 Order 14019 “ 14019 “ requires “ requires our requires our taxpayer-funded our taxpayer-funded federal taxpayer-funded federal agencies federal agencies to agencies to violate to violate the violate the Hatch the Hatch Act Hatch Act and Act and engage and engage in engage in illegal in illegal vote illegal vote harvesting vote harvesting . harvesting . ”'

In [237]:
from sklearn.feature_extraction.text import CountVectorizer

def generate_ngrams(text_column, n):
    vectorizer = CountVectorizer(ngram_range=(n, n), stop_words='english')
    ngram_matrix = vectorizer.fit_transform(text_column)
    ngram_features = vectorizer.get_feature_names_out()
    ngram_counts = ngram_matrix.sum(axis=0).tolist()[0]

    ngram_df = pd.DataFrame({"ngram": ngram_features, "count": ngram_counts})
    ngram_df = ngram_df.sort_values(by="count", ascending=False)
    return ngram_df


for n in [1, 2, 3]:
    print(f"\nTop {n}-grams:")
    ngram_df = generate_ngrams(data["statement"], n)
    print(ngram_df.head(10))

Top 1-grams:
           ngram  count
1387       biden    666
9185       shows    660
2638       covid    503
8916        says    501
10685      video    460
7889   president    429
5602         joe    398
10318      trump    385
88            19    372
7487      people    343

Top 2-grams:
                  ngram  count
19544         joe biden    384
9543           covid 19    356
38638       video shows    355
11959      donald trump    193
26909       photo shows    167
27925     president joe    147
558          19 vaccine     91
24493          new york     79
559         19 vaccines     78
27908  president donald     70

Top 3-grams:
                          ngram  count
29262       president joe biden    147
9849           covid 19 vaccine     91
9850          covid 19 vaccines     78
29244    president donald trump     70
33104            says joe biden     44
11638             died covid 19     24
40451     video shows president     22
34686       shows president joe     22
42146      world economic forum     20
2966   alexandria ocasio cortez     19

Name Entity Recognition NER

In [239]:
import spacy
nlp = spacy.load("en_core_web_sm")

named_entities_list = []
for statement in data['statement']:
  statement = str(statement)
  doc = nlp(statement)
  entities = [ent.text for ent in doc.ents]
  named_entities_list.append(", ".join(entities) if entities else "No entities")

data['Named entities'] = named_entities_list

In [246]:
data['Named entities'][1]

'Mark Zuckerberg, de Meta, Facebook e Instagram'

Author Name Extraction & Visualization

In [240]:
import spacy
from spacy import displacy

In [241]:
authors = data["author"].dropna().unique() #we wnt only unique authors

In [247]:
nlp = spacy.load('en_core_web_sm')

In [248]:
authors_text = ". ".join(authors)
doc = nlp(authors_text)
displacy.render(doc, style="ent", jupyter=True)

parse tree

In [249]:
text = '"I am a Data Science student"'

In [250]:
doc = nlp(text)

In [251]:
displacy.render(doc, style="dep", jupyter=True)